### ISSUE TITLE
Implement Index

### ISSUE THREAD

**Issue by kawasin73** [kawasin73/prsqlite#11]
* [x] sqlite_schema index support #8 
  * CREATE INDEX sql syntax : https://www.sqlite.org/lang_createindex.html
* [x] Single integer column index with `WHERE <index_column> = <integer>`
* [x] Type Conversions Prior To Comparison #7 
  * https://www.sqlite.org/datatype3.html#type_conversions_prior_to_comparison
* [x] Collating Sequences for string comparison #23 
  * https://www.sqlite.org/datatype3.html#collating_sequences
* [x] Multiple columns index
* [ ] autoindex from PRIMARY KEY support
* [ ] `ORDER BY` with index support
